[package]
name = "thunderbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4"
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
lazy_static = "1.4"
rand = "0.8.5"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tera = "1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
